"""
Django settings for massageProject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import environ
from pathlib import Path

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Reading .env file
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'unfold',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rosetta',

    'massageProject.accounts.apps.AccountsConfig',
    'massageProject.main_app.apps.MainAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'massageProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'massageProject.main_app.context_processors.admin_branding',
                'massageProject.accounts.context_processors.turnstile',
            ],
        },
    },
]

WSGI_APPLICATION = 'massageProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'bg'

LANGUAGES = [
    ('bg', _('Bulgarian')),
    ('en', _('English')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    BASE_DIR / 'staticfiles',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'
# VerificationAwareBackend (not ModelBackend/AllowAllUsersModelBackend): authenticate() succeeds for is_active=False users, letting AuthenticationForm.confirm_login_allowed() surface our custom inactive-user message instead of a generic invalid-login error, while get_user()/user_can_authenticate() stay unmodified from ModelBackend so deactivating an account still invalidates that user's existing session on their next request.
AUTHENTICATION_BACKENDS = ['massageProject.accounts.backends.VerificationAwareBackend']

LOGIN_REDIRECT_URL = reverse_lazy('reservation_page')
LOGOUT_REDIRECT_URL = reverse_lazy('index')

# Email Configuration
EMAIL_BACKEND = env('EMAIL_BACKEND', default='massageProject.accounts.email_backend.GmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='webmaster@localhost')

GMAIL_API_CLIENT_ID = env('GMAIL_API_CLIENT_ID', default='')
GMAIL_API_CLIENT_SECRET = env('GMAIL_API_CLIENT_SECRET', default='')
GMAIL_API_REFRESH_TOKEN = env('GMAIL_API_REFRESH_TOKEN', default='')
GMAIL_API_USER_ID = env('GMAIL_API_USER_ID', default='me')

# Cloudflare Turnstile (invisible bot-check widget on the booking auth modal)
TURNSTILE_SITE_KEY = env('TURNSTILE_SITE_KEY', default='')
TURNSTILE_SECRET_KEY = env('TURNSTILE_SECRET_KEY', default='')
# Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "Relax & Health Admin",
    "SITE_HEADER": "Relax & Health",
    "SITE_SYMBOL": "admin_meds",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_LANGUAGES": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            # Studio administration pages.
            {
                "title": _("Студио"),
                "separator": True,
                "items": [
                    {
                        "title": _("Начална страница"),
                        "icon": "home",
                        "link": reverse_lazy("admin:main_app_homepage_changelist"),
                    },
                    {
                        "title": _("Услуги"),
                        "icon": "spa",
                        "link": reverse_lazy("admin:main_app_massage_changelist"),
                    },
                    {
                        "title": _("Терапевти"),
                        "icon": "person",
                        "link": reverse_lazy("admin:main_app_masseur_changelist"),
                    },
                    {
                        "title": _("Работно време"),
                        "icon": "schedule",
                        "link": reverse_lazy("admin:main_app_workinghours_changelist"),
                    },
                    {
                        "title": _("Обекти"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:main_app_messagestudio_changelist"),
                    },
                ],
            },
            # Reservation management pages.
            {
                "title": _("Резервации"),
                "separator": True,
                "items": [
                    {
                        "title": _("Всички резервации"),
                        "icon": "event",
                        "link": reverse_lazy("admin:main_app_messagereservation_changelist"),
                    },
                ],
            },
            # Gallery administration pages.
            {
                "title": _("Галерия"),
                "separator": True,
                "items": [
                    {
                        "title": _("Албуми"),
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:main_app_galleryalbum_changelist"),
                    },
                    {
                        "title": _("Снимки в албум"),
                        "icon": "image",
                        "link": reverse_lazy("admin:main_app_albumphoto_changelist"),
                    },
                ],
            },
            # User and feedback administration pages.
            {
                "title": _("Потребители и Отзиви"),
                "separator": True,
                "items": [
                    {
                        "title": _("Потребители"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_customuser_changelist"),
                    },
                    {
                        "title": _("Коментари"),
                        "icon": "chat",
                        "link": reverse_lazy("admin:main_app_comment_changelist"),
                    },
                ],
            },
        ],
    },
    }
