"""
Django settings for massageProject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import environ
from pathlib import Path

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Reading .env file
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT = True

    # HSTS: tell browsers to only use HTTPS for 1 year
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies must only be sent over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Prevent MIME-type sniffing (explicit, even though Django 3+ defaults True)
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Prevent the site from being embedded in an iframe on other domains
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.forms',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rosetta',
    'django_bleach',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'massageProject.accounts.apps.AccountsConfig',
    'massageProject.main_app.apps.MainAppConfig',
]

# Rosetta must never rely on its library-internal default: staff only,
# stated explicitly so an upgrade or misconfiguration can't widen access.
def _rosetta_staff_only(user):
    return user.is_active and user.is_staff

ROSETTA_ACCESS_CONTROL_FUNCTION = 'massageProject.settings._rosetta_staff_only'

# HTML sanitisation for admin-authored rich-text fields rendered outside the
# admin (e.g. HomePage.privacy_policy_content). Strips scripts and event
# handlers while keeping the formatting markup the content actually uses.
BLEACH_ALLOWED_TAGS = [
    'p', 'br', 'strong', 'em', 'b', 'i', 'u', 'del', 'ul', 'ol', 'li',
    'h1', 'h2', 'h3', 'h4', 'blockquote', 'pre', 'a', 'span', 'div',
]
BLEACH_ALLOWED_ATTRIBUTES = {'a': ['href', 'title', 'rel'], '*': ['style']}
BLEACH_ALLOWED_STYLES = [
    'background', 'border-bottom', 'border-radius', 'color', 'font-family',
    'font-size', 'font-style', 'font-weight', 'margin', 'margin-bottom',
    'margin-top', 'padding', 'padding-bottom', 'padding-left', 'text-align',
]
BLEACH_STRIP_TAGS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'massageProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'massageProject.main_app.context_processors.admin_branding',
                'massageProject.main_app.context_processors.site_configuration',
                'massageProject.accounts.context_processors.turnstile',
            ],
        },
    },
]

WSGI_APPLICATION = 'massageProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'bg'

LANGUAGES = [
    ('bg', _('Bulgarian')),
    ('en', _('English')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    BASE_DIR / 'staticfiles',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'
# VerificationAwareBackend (not ModelBackend/AllowAllUsersModelBackend): authenticate() succeeds for is_active=False users, letting AuthenticationForm.confirm_login_allowed() surface our custom inactive-user message instead of a generic invalid-login error, while get_user()/user_can_authenticate() stay unmodified from ModelBackend so deactivating an account still invalidates that user's existing session on their next request.
AUTHENTICATION_BACKENDS = [
    'massageProject.accounts.backends.VerificationAwareBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = reverse_lazy('reservation_page')
LOGOUT_REDIRECT_URL = reverse_lazy('index')

# Email Configuration
EMAIL_BACKEND = env('EMAIL_BACKEND', default='massageProject.accounts.email_backend.GmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='webmaster@localhost')

GMAIL_API_CLIENT_ID = env('GMAIL_API_CLIENT_ID', default='')
GMAIL_API_CLIENT_SECRET = env('GMAIL_API_CLIENT_SECRET', default='')
GMAIL_API_REFRESH_TOKEN = env('GMAIL_API_REFRESH_TOKEN', default='')
GMAIL_API_USER_ID = env('GMAIL_API_USER_ID', default='me')

# Cloudflare Turnstile (invisible bot-check widget on the booking auth modal)
TURNSTILE_SITE_KEY = env('TURNSTILE_SITE_KEY', default='')
TURNSTILE_SECRET_KEY = env('TURNSTILE_SECRET_KEY', default='')

# django-allauth -- used ONLY for "Continue with Google"; the email/OTP/password
# flows stay on the custom booking auth modal endpoints.
GOOGLE_OAUTH_CLIENT_ID = env('GOOGLE_OAUTH_CLIENT_ID', default='')
GOOGLE_OAUTH_CLIENT_SECRET = env('GOOGLE_OAUTH_CLIENT_SECRET', default='')

ACCOUNT_ADAPTER = 'massageProject.accounts.adapters.ClosedSignupAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'massageProject.accounts.adapters.GoogleSocialAccountAdapter'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
# Every new Google user must pass through the complete-profile form (phone is required).
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_FORMS = {'signup': 'massageProject.accounts.forms.SocialCompleteProfileForm'}
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_OAUTH_CLIENT_ID,
            'secret': GOOGLE_OAUTH_CLIENT_SECRET,
        },
        'SCOPE': ['profile', 'email'],
    },
}

# Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "Relax & Health Admin",
    "SITE_HEADER": "Relax & Health",
    "SITE_SYMBOL": "admin_meds",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_LANGUAGES": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            # Studio administration pages.
            {
                "title": _("Студио"),
                "separator": True,
                "items": [
                    {
                        "title": _("Начална страница"),
                        "icon": "home",
                        "link": reverse_lazy("admin:main_app_homepage_changelist"),
                    },
                    {
                        "title": _("Услуги"),
                        "icon": "spa",
                        "link": reverse_lazy("admin:main_app_service_changelist"),
                    },
                    {
                        "title": _("Терапевти"),
                        "icon": "person",
                        "link": reverse_lazy("admin:main_app_specialist_changelist"),
                    },
                    {
                        "title": _("Работно време"),
                        "icon": "schedule",
                        "link": reverse_lazy("admin:main_app_workinghours_changelist"),
                    },
                    {
                        "title": _("Обекти"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:main_app_businessinfo_changelist"),
                    },
                    {
                        "title": _("Настройки на сайта"),
                        "icon": "palette",
                        "link": reverse_lazy("admin:main_app_siteconfiguration_changelist"),
                    },
                ],
            },
            # Reservation management pages.
            {
                "title": _("Резервации"),
                "separator": True,
                "items": [
                    {
                        "title": _("Всички резервации"),
                        "icon": "event",
                        "link": reverse_lazy("admin:main_app_reservation_changelist"),
                    },
                ],
            },
            # Gallery administration pages.
            {
                "title": _("Галерия"),
                "separator": True,
                "items": [
                    {
                        "title": _("Албуми"),
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:main_app_galleryalbum_changelist"),
                    },
                    {
                        "title": _("Снимки в албум"),
                        "icon": "image",
                        "link": reverse_lazy("admin:main_app_albumphoto_changelist"),
                    },
                ],
            },
            # User and feedback administration pages.
            {
                "title": _("Потребители и Отзиви"),
                "separator": True,
                "items": [
                    {
                        "title": _("Потребители"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_customuser_changelist"),
                    },
                    {
                        "title": _("Коментари"),
                        "icon": "chat",
                        "link": reverse_lazy("admin:main_app_comment_changelist"),
                    },
                ],
            },
        ],
    },
    }
