# Generated by Django 6.0.6 on 2026-06-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Потребител', 'verbose_name_plural': 'Потребители'},
        ),
    ]
