# Generated by Django 6.0.6 on 2026-06-14 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Please correct valid phone number', regex='^(\\+359|0)?8[789]\\d{7}$')]),
        ),
    ]
