# Generated by Django 6.0.6 on 2026-07-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_strip_phone_whitespace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='count_messages',
        ),
    ]
