# Generated by Django 6.0.6 on 2026-10-08 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_count_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please correct valid phone number', regex='^(\\+359|0)?8[789]\\d{7}$')]),
        ),
    ]
