# Generated by Django 5.1.3 on 2024-12-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageStudios',
            new_name='MessageStudio',
        ),
    ]
