# Generated by Django 5.1.3 on 2026-06-03 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masseur',
            name='working_hours',
        ),
        migrations.AlterField(
            model_name='messagereservation',
            name='masseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main_app.masseur'),
        ),
        migrations.AlterField(
            model_name='messagereservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('masseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='main_app.masseur')),
            ],
            options={
                'unique_together': {('masseur', 'day_of_week')},
            },
        ),
    ]
