# Generated by Django 5.1.3 on 2024-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_messagestudios_messagestudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masseur',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='masseur',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='masseur',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masseur',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masseur',
            name='working_hours',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
