# Generated by Django 5.1.3 on 2024-12-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_write_comment', 'Can write a comment')]},
        ),
    ]
