# Generated by Django 5.1.3 on 2024-12-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_masseur_created_at_remove_masseur_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagereservation',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='messagereservation',
            name='masseur',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main_app.masseur'),
        ),
    ]
