# Generated by Django 5.1.3 on 2026-06-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_masseur_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
