# Generated by Django 5.1.3 on 2026-06-05 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment_is_reviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereservation',
            name='status',
            field=models.CharField(choices=[('active', 'Предстояща'), ('completed', 'Завършена'), ('no_show', 'Не се е явил'), ('deleted', 'Отказана')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='messagereservation',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagereservation',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
