# Generated by Django 5.1.3 on 2026-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_messagereservation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='privacy_policy_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
