# Generated by Django 5.1.3 on 2026-06-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_comment_user_alter_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_label', models.CharField(help_text='напр. "Понеделник до Петък"', max_length=100, verbose_name='Ден / период')),
                ('hours', models.CharField(blank=True, help_text='напр. "9:00 - 18:00" — оставете празно за "Почивен ден"', max_length=50, verbose_name='Часове')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ред')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_working_hours', to='main_app.homepage')),
            ],
            options={
                'verbose_name': 'Работно време на студиото',
                'verbose_name_plural': 'Работно време на студиото',
                'ordering': ['order'],
            },
        ),
    ]
