# Generated by Django 5.1.3 on 2026-06-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_studioworkinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='privacy_policy_content_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='privacy_policy_content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='alt_text_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='alt_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='name_bg',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='name_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='short_description_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='short_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masseur',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='masseur',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='masseur',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masseur',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='address_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studioworkinghours',
            name='day_label_bg',
            field=models.CharField(help_text='напр. "Понеделник до Петък"', max_length=100, null=True, verbose_name='Ден / период'),
        ),
        migrations.AddField(
            model_name='studioworkinghours',
            name='day_label_en',
            field=models.CharField(help_text='напр. "Понеделник до Петък"', max_length=100, null=True, verbose_name='Ден / период'),
        ),
        migrations.AddField(
            model_name='studioworkinghours',
            name='hours_bg',
            field=models.CharField(blank=True, help_text='напр. "9:00 - 18:00" — оставете празно за "Почивен ден"', max_length=50, null=True, verbose_name='Часове'),
        ),
        migrations.AddField(
            model_name='studioworkinghours',
            name='hours_en',
            field=models.CharField(blank=True, help_text='напр. "9:00 - 18:00" — оставете празно за "Почивен ден"', max_length=50, null=True, verbose_name='Часове'),
        ),
    ]
