# Generated by Django 6.0.6 on 2026-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_homepage_description_bg_homepage_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='title',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='title_bg',
            new_name='brand_name_bg',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='title_en',
            new_name='brand_name_en',
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
