# Generated by Django 6.0.6 on 2026-06-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_title_homepage_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_tagline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_tagline_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_tagline_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
