# Generated by Django 6.0.6 on 2026-06-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_comment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massage',
            options={'verbose_name': 'Масаж', 'verbose_name_plural': 'Масажи'},
        ),
        migrations.AlterModelOptions(
            name='masseur',
            options={'verbose_name': 'Терапевт', 'verbose_name_plural': 'Терапевти'},
        ),
        migrations.AlterModelOptions(
            name='messagestudio',
            options={'verbose_name': 'Студио', 'verbose_name_plural': 'Студиа'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name': 'Работно време', 'verbose_name_plural': 'Работно време'},
        ),
    ]
