# Generated by Django 6.0.6 on 2026-06-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_massage_options_alter_masseur_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='main_app.messagereservation', verbose_name='резервация'),
        ),
    ]
