# Generated by Django 6.0.6 on 2026-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_comment_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментари'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерия', 'verbose_name_plural': 'Галерии'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Изображение в галерия', 'verbose_name_plural': 'Изображения в галерия'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Начална страница', 'verbose_name_plural': 'Начални страници'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='messagereservation',
            options={'verbose_name': 'Резервация', 'verbose_name_plural': 'Резервации'},
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='email_address',
            field=models.EmailField(default='svetlana_yaneva81@abv.bg', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagestudio',
            name='tik_tok_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
