# Generated by Django 6.0.6 on 2026-06-15 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_comment_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('name_bg', models.CharField(max_length=100, null=True, verbose_name='Наименование')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Наименование')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ред')),
            ],
            options={
                'verbose_name': 'Група услуги',
                'verbose_name_plural': 'Групи услуги',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='massage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='massages', to='main_app.servicegroup', verbose_name='Група'),
        ),
    ]
