# Generated by Django 6.0.6 on 2026-06-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_servicegroup_massage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Кратко описание'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='short_description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Кратко описание'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Кратко описание'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заглавие'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_bg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('title_bg', models.CharField(max_length=255, null=True, verbose_name='Заглавие')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заглавие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_bg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ред')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='main_app.gallery', verbose_name='Галерия')),
            ],
            options={
                'verbose_name': 'Албум',
                'verbose_name_plural': 'Албуми',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/albums/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Алт текст')),
                ('alt_text_bg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Алт текст')),
                ('alt_text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Алт текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ред')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_app.galleryalbum', verbose_name='Албум')),
            ],
            options={
                'verbose_name': 'Снимка в албум',
                'verbose_name_plural': 'Снимки в албум',
                'ordering': ['order'],
            },
        ),
    ]
