# Generated by Django 6.0.6 on 2026-06-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_gallery_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryalbum',
            name='gallery',
        ),
    ]
