# Generated by Django 6.0.6 on 2026-07-14 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_galleryalbum_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='messagereservation',
            name='additional_text',
            field=models.TextField(blank=True, default='', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
