# Generated by Django 6.0.6 on 2026-07-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_rename_massage_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Masseur',
            new_name='Specialist',
        ),
        migrations.RenameField(
            model_name='messagereservation',
            old_name='masseur',
            new_name='specialist',
        ),
        migrations.RenameField(
            model_name='workinghours',
            old_name='masseur',
            new_name='specialist',
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('specialist', 'day_of_week')},
        ),
        migrations.AlterField(
            model_name='specialist',
            name='image',
            field=models.ImageField(upload_to='specialists/'),
        ),
    ]
