# Generated by Django 6.0.6 on 2026-07-19 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_rename_masseur_specialist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageStudio',
            new_name='BusinessInfo',
        ),
        migrations.RenameModel(
            old_name='StudioWorkingHours',
            new_name='BusinessWorkingHours',
        ),
        migrations.RenameModel(
            old_name='MessageReservation',
            new_name='Reservation',
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='main_image',
            field=models.ImageField(upload_to='business/'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='home_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_working_hours', to='main_app.homepage'),
        ),
    ]
