# Generated by Django 6.0.6 on 2026-07-20 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_rename_models_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#4A3728', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основен цвят')),
                ('primary_light_color', models.CharField(default='#6D5442', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основен цвят (светъл)')),
                ('secondary_color', models.CharField(default='#C2A38E', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Вторичен цвят')),
                ('accent_color', models.CharField(default='#8E735B', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Акцентен цвят')),
                ('background_color', models.CharField(default='#FAF7F2', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон')),
                ('text_color', models.CharField(default='#2D241E', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Текст')),
                ('text_muted_color', models.CharField(default='#6B5E55', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Текст (приглушен)')),
                ('font_pair', models.CharField(choices=[('playfair_montserrat', 'Playfair Display + Montserrat'), ('cormorant_lato', 'Cormorant Garamond + Lato'), ('poppins_opensans', 'Poppins + Open Sans'), ('merriweather_sourcesans', 'Merriweather + Source Sans 3'), ('raleway_roboto', 'Raleway + Roboto')], default='playfair_montserrat', max_length=30, verbose_name='Двойка шрифтове')),
                ('style_preset', models.CharField(choices=[('soft', 'Мек (текущи radius и сенки)'), ('sharp', 'Остър (минимални radius, плоски сенки)'), ('round', 'Заоблен (pill бутони, големи radius)')], default='soft', max_length=10, verbose_name='Стил (форми и сенки)')),
                ('hero_variant', models.CharField(choices=[('split', 'Split — текст и снимка една до друга'), ('carousel', 'Carousel — въртяща се галерия'), ('fullbleed', 'Fullbleed — снимка на цяла ширина')], default='split', max_length=10, verbose_name='Начален банер')),
                ('service_singular', models.CharField(default='услуга', max_length=50, verbose_name='Услуга (ед. число)')),
                ('service_plural', models.CharField(default='услуги', max_length=50, verbose_name='Услуги (мн. число)')),
                ('specialist_singular', models.CharField(default='специалист', max_length=50, verbose_name='Специалист (ед. число)')),
                ('specialist_plural', models.CharField(default='специалисти', max_length=50, verbose_name='Специалисти (мн. число)')),
                ('booking_enabled', models.BooleanField(default=True, verbose_name='Резервации активни')),
                ('comments_enabled', models.BooleanField(default=True, verbose_name='Коментари активни')),
                ('google_login_enabled', models.BooleanField(default=True, verbose_name='Вход с Google активен')),
            ],
            options={
                'verbose_name': 'Настройки на сайта',
                'verbose_name_plural': 'Настройки на сайта',
            },
        ),
    ]
