# Generated by Django 6.0.6 on 2026-07-20 19:44

from django.db import migrations


def create_default_site_configuration(apps, schema_editor):
    SiteConfiguration = apps.get_model('main_app', 'SiteConfiguration')
    SiteConfiguration.objects.get_or_create(pk=1)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_siteconfiguration'),
    ]

    operations = [
        migrations.RunPython(create_default_site_configuration, noop_reverse),
    ]
