# Generated by Django 6.0.6 on 2026-07-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_seed_site_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_plural_bg',
            field=models.CharField(default='услуги', max_length=50, null=True, verbose_name='Услуги (мн. число)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_plural_en',
            field=models.CharField(default='услуги', max_length=50, null=True, verbose_name='Услуги (мн. число)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_singular_bg',
            field=models.CharField(default='услуга', max_length=50, null=True, verbose_name='Услуга (ед. число)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='service_singular_en',
            field=models.CharField(default='услуга', max_length=50, null=True, verbose_name='Услуга (ед. число)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='specialist_plural_bg',
            field=models.CharField(default='специалисти', max_length=50, null=True, verbose_name='Специалисти (мн. число)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='specialist_plural_en',
            field=models.CharField(default='специалисти', max_length=50, null=True, verbose_name='Специалисти (мн. число)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='specialist_singular_bg',
            field=models.CharField(default='специалист', max_length=50, null=True, verbose_name='Специалист (ед. число)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='specialist_singular_en',
            field=models.CharField(default='специалист', max_length=50, null=True, verbose_name='Специалист (ед. число)'),
        ),
    ]
