# Generated by Django 6.0.6 on 2026-07-22 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_siteconfiguration_service_plural_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='border_color',
            field=models.CharField(default='#4A3728', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цвят на рамки'),
        ),
    ]
