# Generated by Django 6.0.6 on 2026-07-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_siteconfiguration_border_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='credentials',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='credentials_bg',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='credentials_en',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='faq',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='faq_bg',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='faq_en',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
