# Generated by Django 6.0.6 on 2026-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_businessinfo_credentials_businessinfo_credentials_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='credentials',
            field=models.JSONField(blank=True, default=dict, help_text='JSON обект с два списъка — "training" и "recognition". Всеки елемент: title, subtitle, по избор year и description. Празен списък скрива съответната група. Пример: {"training": [{"title": "Шведски масаж", "subtitle": "Виенски институт", "year": "2019", "description": "..."}], "recognition": []}'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='credentials_bg',
            field=models.JSONField(blank=True, default=dict, help_text='JSON обект с два списъка — "training" и "recognition". Всеки елемент: title, subtitle, по избор year и description. Празен списък скрива съответната група. Пример: {"training": [{"title": "Шведски масаж", "subtitle": "Виенски институт", "year": "2019", "description": "..."}], "recognition": []}', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='credentials_en',
            field=models.JSONField(blank=True, default=dict, help_text='JSON обект с два списъка — "training" и "recognition". Всеки елемент: title, subtitle, по избор year и description. Празен списък скрива съответната група. Пример: {"training": [{"title": "Шведски масаж", "subtitle": "Виенски институт", "year": "2019", "description": "..."}], "recognition": []}', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='JSON списък от въпроси и отговори. Празен списък скрива секцията. Пример: [{"question": "Приемате ли без резервация?", "answer": "Не, само с предварителна резервация."}]'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='faq_bg',
            field=models.JSONField(blank=True, default=list, help_text='JSON списък от въпроси и отговори. Празен списък скрива секцията. Пример: [{"question": "Приемате ли без резервация?", "answer": "Не, само с предварителна резервация."}]', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='faq_en',
            field=models.JSONField(blank=True, default=list, help_text='JSON списък от въпроси и отговори. Празен списък скрива секцията. Пример: [{"question": "Приемате ли без резервация?", "answer": "Не, само с предварителна резервация."}]', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='stats',
            field=models.JSONField(blank=True, default=dict, help_text='JSON обект с показатели (изберете кои да покажете, останалите се скриват): {"years_of_practice": "8+", "clients_served": "500+", "average_rating": "4.9", "certifications_count": "12"}'),
        ),
    ]
