# Generated by Django 6.0.6 on 2026-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_businessinfo_credentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='main_image',
            field=models.ImageField(help_text='Снимката се показва в естествените си пропорции (без изрязване), с ограничена максимална ширина. За симетричен и професионален вид препоръчваме портретна или квадратна снимка (съотношение между 3:4 и 1:1), минимум 800px на по-късата страна. Много издължени (панорамни или тесни) снимки могат да изглеждат непропорционално до текста.', upload_to='business/'),
        ),
    ]
