# Generated by Django 6.0.6 on 2026-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_reservation_unique_active_reservation_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Предстояща'), ('completed', 'Завършена'), ('no_show', 'Не се е явил'), ('deleted', 'Отказана')], db_index=True, default='active', max_length=20),
        ),
    ]
