# Generated by Django 6.0.6 on 2026-07-24 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_comment_is_reviewed_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Използва се като алтернативен текст (alt) за тази снимка.', max_length=255, verbose_name='Алт текст'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='alt_text_bg',
            field=models.CharField(blank=True, help_text='Използва се като алтернативен текст (alt) за тази снимка.', max_length=255, null=True, verbose_name='Алт текст'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='alt_text_en',
            field=models.CharField(blank=True, help_text='Използва се като алтернативен текст (alt) за тази снимка.', max_length=255, null=True, verbose_name='Алт текст'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='image',
            field=models.ImageField(help_text='Показва се на страницата на албума, а ако е първата снимка в него — и като корична снимка на албума на страницата с галерии.', upload_to='gallery/albums/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Определя реда, в който снимките се показват в албума, и коя снимка се използва като корична (първата по ред).', verbose_name='Ред'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='address',
            field=models.CharField(help_text='Показва се в контактната карта в профила на клиента и в долния колонтитул (footer) на сайта.', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='address_bg',
            field=models.CharField(help_text='Показва се в контактната карта в профила на клиента и в долния колонтитул (footer) на сайта.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='address_en',
            field=models.CharField(help_text='Показва се в контактната карта в профила на клиента и в долния колонтитул (footer) на сайта.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='credentials',
            field=models.JSONField(blank=True, default=dict, help_text='JSON обект с два списъка — "training" и "recognition". Всеки елемент: title, subtitle, по избор year и description. Празен списък скрива съответната група. Пример: {"training": [{"title": "Шведски масаж", "subtitle": "Виенски институт", "year": "2019", "description": "..."}], "recognition": []}. Показва се като секция "Обучения/Признания" в страница "За нас".'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='credentials_bg',
            field=models.JSONField(blank=True, default=dict, help_text='JSON обект с два списъка — "training" и "recognition". Всеки елемент: title, subtitle, по избор year и description. Празен списък скрива съответната група. Пример: {"training": [{"title": "Шведски масаж", "subtitle": "Виенски институт", "year": "2019", "description": "..."}], "recognition": []}. Показва се като секция "Обучения/Признания" в страница "За нас".', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='credentials_en',
            field=models.JSONField(blank=True, default=dict, help_text='JSON обект с два списъка — "training" и "recognition". Всеки елемент: title, subtitle, по избор year и description. Празен списък скрива съответната група. Пример: {"training": [{"title": "Шведски масаж", "subtitle": "Виенски институт", "year": "2019", "description": "..."}], "recognition": []}. Показва се като секция "Обучения/Признания" в страница "За нас".', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='description',
            field=models.TextField(help_text='Показва се като основен текст в страница "За нас".'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='description_bg',
            field=models.TextField(help_text='Показва се като основен текст в страница "За нас".', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='description_en',
            field=models.TextField(help_text='Показва се като основен текст в страница "За нас".', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='email_address',
            field=models.EmailField(help_text='Показва се в долния колонтитул (footer) на сайта като mailto линк.', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Показва се като социална икона в долния колонтитул (footer) на сайта.', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='JSON списък от въпроси и отговори. Празен списък скрива секцията. Пример: [{"question": "Приемате ли без резервация?", "answer": "Не, само с предварителна резервация."}]. Показва се като разгъващ се списък с въпроси и отговори в страница "За нас".'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='faq_bg',
            field=models.JSONField(blank=True, default=list, help_text='JSON списък от въпроси и отговори. Празен списък скрива секцията. Пример: [{"question": "Приемате ли без резервация?", "answer": "Не, само с предварителна резервация."}]. Показва се като разгъващ се списък с въпроси и отговори в страница "За нас".', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='faq_en',
            field=models.JSONField(blank=True, default=list, help_text='JSON списък от въпроси и отговори. Празен списък скрива секцията. Пример: [{"question": "Приемате ли без резервация?", "answer": "Не, само с предварителна резервация."}]. Показва се като разгъващ се списък с въпроси и отговори в страница "За нас".', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Показва се като социална икона в долния колонтитул (footer) на сайта.', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='main_image',
            field=models.ImageField(help_text='Снимката се показва в естествените си пропорции (без изрязване), с ограничена максимална ширина. За симетричен и професионален вид препоръчваме портретна или квадратна снимка (съотношение между 3:4 и 1:1), минимум 800px на по-късата страна. Много издължени (панорамни или тесни) снимки могат да изглеждат непропорционално до текста. Показва се като главна снимка в страница "За нас".', upload_to='business/'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='name',
            field=models.CharField(help_text='Използва се като алтернативен текст (alt) на снимката на студиото в страница "За нас".', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='name_bg',
            field=models.CharField(help_text='Използва се като алтернативен текст (alt) на снимката на студиото в страница "За нас".', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='name_en',
            field=models.CharField(help_text='Използва се като алтернативен текст (alt) на снимката на студиото в страница "За нас".', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='phone',
            field=models.CharField(blank=True, help_text='Показва се в профила на клиента и в долния колонтитул (footer) на сайта като линк за обаждане.', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='stats',
            field=models.JSONField(blank=True, default=dict, help_text='JSON обект с показатели (изберете кои да покажете, останалите се скриват): {"years_of_practice": "8+", "clients_served": "500+", "average_rating": "4.9", "certifications_count": "12"}. years_of_practice, clients_served и certifications_count се показват като карти с показатели в страница "За нас".'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='tik_tok_link',
            field=models.URLField(blank=True, help_text='Показва се като социална икона в долния колонтитул (footer) на сайта.', null=True),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='day_label',
            field=models.CharField(help_text='напр. "Понеделник до Петък". Показва се в списъка "Работно време" на началната страница и в профила на клиента.', max_length=100, verbose_name='Ден / период'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='day_label_bg',
            field=models.CharField(help_text='напр. "Понеделник до Петък". Показва се в списъка "Работно време" на началната страница и в профила на клиента.', max_length=100, null=True, verbose_name='Ден / период'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='day_label_en',
            field=models.CharField(help_text='напр. "Понеделник до Петък". Показва се в списъка "Работно време" на началната страница и в профила на клиента.', max_length=100, null=True, verbose_name='Ден / период'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='hours',
            field=models.CharField(blank=True, help_text='напр. "9:00 - 18:00" — оставете празно за "Почивен ден". Показва се в списъка "Работно време" на началната страница и в профила на клиента.', max_length=50, verbose_name='Часове'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='hours_bg',
            field=models.CharField(blank=True, help_text='напр. "9:00 - 18:00" — оставете празно за "Почивен ден". Показва се в списъка "Работно време" на началната страница и в профила на клиента.', max_length=50, null=True, verbose_name='Часове'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='hours_en',
            field=models.CharField(blank=True, help_text='напр. "9:00 - 18:00" — оставете празно за "Почивен ден". Показва се в списъка "Работно време" на началната страница и в профила на клиента.', max_length=50, null=True, verbose_name='Часове'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Определя реда, в който тези редове се показват.', verbose_name='Ред'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, help_text='Показва се като име на автора в секцията с отзиви на началната страница и на страницата с всички отзиви.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Показва се като текст на отзива в секцията с отзиви на началната страница и на страницата с всички отзиви.', max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Показва се като дата на отзива на страницата с всички отзиви.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_reviewed',
            field=models.BooleanField(db_index=True, default=False, help_text='Трябва да е отметнато, за да се показва този отзив публично в секцията с отзиви на началната страница и на страницата с всички отзиви.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=5, help_text='Показва се като звезден рейтинг в секцията с отзиви на началната страница.'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(help_text='Първите 3 снимки се показват в секцията с галерия на началната страница.', related_name='galleries', through='main_app.GalleryImage', to='main_app.image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='short_description',
            field=models.TextField(blank=True, help_text='Показва се като заглавие на секцията с галерия на началната страница.', verbose_name='Кратко описание'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='short_description_bg',
            field=models.TextField(blank=True, help_text='Показва се като заглавие на секцията с галерия на началната страница.', null=True, verbose_name='Кратко описание'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Показва се като заглавие на секцията с галерия на началната страница.', null=True, verbose_name='Кратко описание'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, help_text='Показва се като малък надпис над секцията с галерия на началната страница.', max_length=255, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_bg',
            field=models.CharField(blank=True, help_text='Показва се като малък надпис над секцията с галерия на началната страница.', max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(blank=True, help_text='Показва се като малък надпис над секцията с галерия на началната страница.', max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='description',
            field=models.TextField(blank=True, help_text='Показва се на собствената страница на албума, а за първия по ред албум — и в плочката му на страницата с галерии.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='description_bg',
            field=models.TextField(blank=True, help_text='Показва се на собствената страница на албума, а за първия по ред албум — и в плочката му на страницата с галерии.', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='description_en',
            field=models.TextField(blank=True, help_text='Показва се на собствената страница на албума, а за първия по ред албум — и в плочката му на страницата с галерии.', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Определя реда, в който албумите се показват на страницата с галерии.', verbose_name='Ред'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='slug',
            field=models.SlugField(help_text='Използва се за изграждане на адреса (URL) на страницата на този албум.', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='title',
            field=models.CharField(help_text='Показва се като заглавие на албума на страницата с галерии и на собствената му страница.', max_length=255, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='title_bg',
            field=models.CharField(help_text='Показва се като заглавие на албума на страницата с галерии и на собствената му страница.', max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='title_en',
            field=models.CharField(help_text='Показва се като заглавие на албума на страницата с галерии и на собствената му страница.', max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brand_name',
            field=models.CharField(help_text='Показва се като име на сайта в началния банер, в алтернативния текст (alt) на логото в горния колонтитул, в реда за авторски права в долния колонтитул (footer), както и в имейлите до клиентите (кодове за резервация, смяна на парола).', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brand_name_bg',
            field=models.CharField(help_text='Показва се като име на сайта в началния банер, в алтернативния текст (alt) на логото в горния колонтитул, в реда за авторски права в долния колонтитул (footer), както и в имейлите до клиентите (кодове за резервация, смяна на парола).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brand_name_en',
            field=models.CharField(help_text='Показва се като име на сайта в началния банер, в алтернативния текст (alt) на логото в горния колонтитул, в реда за авторски права в долния колонтитул (footer), както и в имейлите до клиентите (кодове за резервация, смяна на парола).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(help_text='Показва се като подзаглавие в началния банер на началната страница.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description_bg',
            field=models.TextField(help_text='Показва се като подзаглавие в началния банер на началната страница.', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description_en',
            field=models.TextField(help_text='Показва се като подзаглавие в началния банер на началната страница.', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_tagline',
            field=models.TextField(blank=True, help_text='Показва се като кратък текст (tagline) в долния колонтитул (footer) на сайта.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_tagline_bg',
            field=models.TextField(blank=True, help_text='Показва се като кратък текст (tagline) в долния колонтитул (footer) на сайта.', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_tagline_en',
            field=models.TextField(blank=True, help_text='Показва се като кратък текст (tagline) в долния колонтитул (footer) на сайта.', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, help_text='Показва се като лого в горния колонтитул на сайта и в имейлите до клиентите.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='privacy_policy_content',
            field=models.TextField(blank=True, help_text='Показва се изцяло на страницата "Политика за поверителност".', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='privacy_policy_content_bg',
            field=models.TextField(blank=True, help_text='Показва се изцяло на страницата "Политика за поверителност".', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='privacy_policy_content_en',
            field=models.TextField(blank=True, help_text='Показва се изцяло на страницата "Политика за поверителност".', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(help_text='Използва се като алтернативен текст (alt) за тази снимка в секцията с галерия на началната страница.', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text_bg',
            field=models.CharField(help_text='Използва се като алтернативен текст (alt) за тази снимка в секцията с галерия на началната страница.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text_en',
            field=models.CharField(help_text='Използва се като алтернативен текст (alt) за тази снимка в секцията с галерия на началната страница.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Показва се в секцията с галерия на началната страница.', upload_to='studios/gallery/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='additional_text',
            field=models.TextField(blank=True, default='', help_text='Показва се на клиента при преглед, редакция или отказ на резервацията му.', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(db_index=True, help_text='Показва се в потвърждението на резервацията и в списъка с резервации в профила на клиента.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(help_text='Показва се в потвърждението на резервацията и в списъка с резервации в профила на клиента.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main_app.service'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='specialist',
            field=models.ForeignKey(help_text='Показва се в потвърждението на резервацията и в списъка с резервации в профила на клиента.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main_app.specialist'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Предстояща'), ('completed', 'Завършена'), ('no_show', 'Не се е явил'), ('deleted', 'Отказана')], db_index=True, default='active', help_text='Определя дали резервацията се показва като предстояща или минала в профила на клиента (или изобщо не се показва, ако е отказана).', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(help_text='Показва се в потвърждението на резервацията и в списъка с резервации в профила на клиента.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Показва се на страницата с детайли за услугата.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_bg',
            field=models.TextField(help_text='Показва се на страницата с детайли за услугата.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(help_text='Показва се на страницата с детайли за услугата.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_in_minutes',
            field=models.IntegerField(help_text='Показва се на страницата с услуги, страницата с детайли за услугата и предпочитаните услуги на началната страница; използва се и за изчисляване на свободните часове за резервация.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Определя под кой таб-категория е класирана услугата на страницата с услуги.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='main_app.servicegroup', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='service',
            name='home_page',
            field=models.BooleanField(default=False, help_text='Когато е отметнато, услугата се показва в секция "Предпочитани услуги" на началната страница (максимум 3).'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(help_text='Показва се на картата в страницата с услуги, в предпочитаните услуги на началната страница и на страницата с детайли за услугата. Ако е празно, се показва градиентен placeholder.', upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Показва се в предпочитаните услуги на началната страница, на страницата с услуги, на страницата с детайли за услугата и навсякъде в процеса на резервация.', max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_bg',
            field=models.CharField(help_text='Показва се в предпочитаните услуги на началната страница, на страницата с услуги, на страницата с детайли за услугата и навсякъде в процеса на резервация.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(help_text='Показва се в предпочитаните услуги на началната страница, на страницата с услуги, на страницата с детайли за услугата и навсякъде в процеса на резервация.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Показва се на страницата с услуги, страницата с детайли за услугата и предпочитаните услуги на началната страница.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(help_text='Кратък текст, показван в предпочитаните услуги на началната страница и във всяка карта на страницата с услуги.', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_bg',
            field=models.CharField(help_text='Кратък текст, показван в предпочитаните услуги на началната страница и във всяка карта на страницата с услуги.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(help_text='Кратък текст, показван в предпочитаните услуги на началната страница и във всяка карта на страницата с услуги.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='name',
            field=models.CharField(help_text='Показва се като таб-категория на страницата с услуги.', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='name_bg',
            field=models.CharField(help_text='Показва се като таб-категория на страницата с услуги.', max_length=100, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='name_en',
            field=models.CharField(help_text='Показва се като таб-категория на страницата с услуги.', max_length=100, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Определя реда, в който категориите се показват на страницата с услуги.', verbose_name='Ред'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='accent_color',
            field=models.CharField(default='#8E735B', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Акцентен цвят'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='background_color',
            field=models.CharField(default='#FAF7F2', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='booking_enabled',
            field=models.BooleanField(default=True, help_text='Когато е изключено, скрива всички бутони/линкове за резервация по целия сайт (горно меню, начална страница, страница с услуги, детайли за услуга, профил на клиента).', verbose_name='Резервации активни'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='border_color',
            field=models.CharField(default='#4A3728', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цвят на рамки'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='comments_enabled',
            field=models.BooleanField(default=True, help_text='Когато е изключено, скрива секцията с отзиви на началната страница.', verbose_name='Коментари активни'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='font_pair',
            field=models.CharField(choices=[('playfair_montserrat', 'Playfair Display + Montserrat'), ('cormorant_lato', 'Cormorant Garamond + Lato'), ('poppins_opensans', 'Poppins + Open Sans'), ('merriweather_sourcesans', 'Merriweather + Source Sans 3'), ('raleway_roboto', 'Raleway + Roboto')], default='playfair_montserrat', help_text='Шрифт по цялата тема на сайта, използван на всички страници.', max_length=30, verbose_name='Двойка шрифтове'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='google_login_enabled',
            field=models.BooleanField(default=True, help_text='Когато е изключено, скрива опцията "Вход с Google" в модала за вход.', verbose_name='Вход с Google активен'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_variant',
            field=models.CharField(choices=[('split', 'Split — текст и снимка една до друга'), ('carousel', 'Carousel — въртяща се галерия'), ('fullbleed', 'Fullbleed — снимка на цяла ширина')], default='split', help_text='Определя кой изглед на банера се използва на началната страница.', max_length=10, verbose_name='Начален банер'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_color',
            field=models.CharField(default='#4A3728', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основен цвят'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_light_color',
            field=models.CharField(default='#6D5442', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основен цвят (светъл)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=models.CharField(default='#C2A38E', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Вторичен цвят'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='service_plural',
            field=models.CharField(default='услуги', help_text='Използва се навсякъде, където сайтът се обръща към "услуги" — напр. страницата за резервация и профила на клиента.', max_length=50, verbose_name='Услуги (мн. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='service_plural_bg',
            field=models.CharField(default='услуги', help_text='Използва се навсякъде, където сайтът се обръща към "услуги" — напр. страницата за резервация и профила на клиента.', max_length=50, null=True, verbose_name='Услуги (мн. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='service_plural_en',
            field=models.CharField(default='услуги', help_text='Използва се навсякъде, където сайтът се обръща към "услуги" — напр. страницата за резервация и профила на клиента.', max_length=50, null=True, verbose_name='Услуги (мн. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='service_singular',
            field=models.CharField(default='услуга', help_text='Използва се навсякъде, където сайтът се обръща към "услуга" — напр. страницата за резервация и профила на клиента.', max_length=50, verbose_name='Услуга (ед. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='service_singular_bg',
            field=models.CharField(default='услуга', help_text='Използва се навсякъде, където сайтът се обръща към "услуга" — напр. страницата за резервация и профила на клиента.', max_length=50, null=True, verbose_name='Услуга (ед. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='service_singular_en',
            field=models.CharField(default='услуга', help_text='Използва се навсякъде, където сайтът се обръща към "услуга" — напр. страницата за резервация и профила на клиента.', max_length=50, null=True, verbose_name='Услуга (ед. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='specialist_plural',
            field=models.CharField(default='специалисти', help_text='Използва се навсякъде, където сайтът се обръща към "специалисти" — напр. страницата за резервация и профила на клиента.', max_length=50, verbose_name='Специалисти (мн. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='specialist_plural_bg',
            field=models.CharField(default='специалисти', help_text='Използва се навсякъде, където сайтът се обръща към "специалисти" — напр. страницата за резервация и профила на клиента.', max_length=50, null=True, verbose_name='Специалисти (мн. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='specialist_plural_en',
            field=models.CharField(default='специалисти', help_text='Използва се навсякъде, където сайтът се обръща към "специалисти" — напр. страницата за резервация и профила на клиента.', max_length=50, null=True, verbose_name='Специалисти (мн. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='specialist_singular',
            field=models.CharField(default='специалист', help_text='Използва се навсякъде, където сайтът се обръща към "специалист" — напр. страницата за резервация и профила на клиента.', max_length=50, verbose_name='Специалист (ед. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='specialist_singular_bg',
            field=models.CharField(default='специалист', help_text='Използва се навсякъде, където сайтът се обръща към "специалист" — напр. страницата за резервация и профила на клиента.', max_length=50, null=True, verbose_name='Специалист (ед. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='specialist_singular_en',
            field=models.CharField(default='специалист', help_text='Използва се навсякъде, където сайтът се обръща към "специалист" — напр. страницата за резервация и профила на клиента.', max_length=50, null=True, verbose_name='Специалист (ед. число)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='style_preset',
            field=models.CharField(choices=[('soft', 'Мек (текущи radius и сенки)'), ('sharp', 'Остър (минимални radius, плоски сенки)'), ('round', 'Заоблен (pill бутони, големи radius)')], default='soft', help_text='Стил на форми и сенки (заобляне на ъгли, бутони, карти) по цялата тема на сайта.', max_length=10, verbose_name='Стил (форми и сенки)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='text_color',
            field=models.CharField(default='#2D241E', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='text_muted_color',
            field=models.CharField(default='#6B5E55', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Текст (приглушен)'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='description',
            field=models.TextField(help_text='Показва се като кратко био в селектора на терапевти на страницата за резервация.'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='description_bg',
            field=models.TextField(help_text='Показва се като кратко био в селектора на терапевти на страницата за резервация.', null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='description_en',
            field=models.TextField(help_text='Показва се като кратко био в селектора на терапевти на страницата за резервация.', null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(help_text='Показва се в селектора на терапевти на страницата за резервация и в профила на клиента (предстоящи/минали резервации).', max_length=255),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name_bg',
            field=models.CharField(help_text='Показва се в селектора на терапевти на страницата за резервация и в профила на клиента (предстоящи/минали резервации).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name_en',
            field=models.CharField(help_text='Показва се в селектора на терапевти на страницата за резервация и в профила на клиента (предстоящи/минали резервации).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(help_text='Не се показва директно, но определя кои часове се предлагат на клиентите при резервация с този терапевт в този ден.'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(help_text='Не се показва директно, но определя кои часове се предлагат на клиентите при резервация с този терапевт в този ден.'),
        ),
    ]
