# Generated by Django 6.0.6 on 2026-07-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_albumphoto_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main_app.gallery'),
        ),
    ]
