# Generated by Django 6.0.6 on 2026-07-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_reservation_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Показва се на картата в страницата с услуги, в предпочитаните услуги на началната страница и на страницата с детайли за услугата. Ако е празно, се показва градиентен placeholder.', null=True, upload_to='services/'),
        ),
    ]
