# Generated by Django 6.0.6 on 2026-07-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='send_user_notification_on_gallery_creation',
            field=models.BooleanField(default=False, help_text='Да бъде ли изпратено уведомление до клиента при създаване на галерия?'),
        ),
    ]
