# Generated by Django 6.0.6 on 2026-07-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_reservation_send_user_notification_on_gallery_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order'], 'verbose_name': 'Галерия', 'verbose_name_plural': 'Галерии'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, help_text='За албуми: показва се на собствената страница на албума, а за първия по ред албум — и в плочката му на страницата с галерии. За началната страница: показва се като заглавие на секцията с галерия.', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_bg',
            field=models.TextField(blank=True, help_text='За албуми: показва се на собствената страница на албума, а за първия по ред албум — и в плочката му на страницата с галерии. За началната страница: показва се като заглавие на секцията с галерия.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_en',
            field=models.TextField(blank=True, help_text='За албуми: показва се на собствената страница на албума, а за първия по ред албум — и в плочката му на страницата с галерии. За началната страница: показва се като заглавие на секцията с галерия.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_type',
            field=models.CharField(choices=[('homepage', 'Начална страница'), ('reservation', 'Резервация'), ('album', 'Албум')], default='album', help_text='Определя къде се показва тази галерия: "Начална страница" — секцията с галерия на началната страница (може да има само една); "Резервация" — снимки, свързани с конкретна резервация; "Албум" — показва се като самостоятелен албум на страницата с галерии.', max_length=20, verbose_name='Тип галерия'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Определя реда, в който албумите се показват на страницата с галерии.', verbose_name='Ред'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, help_text='Използва се за изграждане на адреса (URL) на страницата на албума. Не се използва за другите типове галерии.', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images_tmp', to='main_app.gallery', verbose_name='Галерия'),
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Определя реда, в който снимките се показват в галерията/албума, и коя се използва като корична (първата по ред).', verbose_name='Ред'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, help_text='За албуми: показва се като заглавие на албума на страницата с галерии и на собствената му страница (задължително за албуми). За началната страница: показва се като малък надпис над секцията с галерия.', max_length=255, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_bg',
            field=models.CharField(blank=True, help_text='За албуми: показва се като заглавие на албума на страницата с галерии и на собствената му страница (задължително за албуми). За началната страница: показва се като малък надпис над секцията с галерия.', max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(blank=True, help_text='За албуми: показва се като заглавие на албума на страницата с галерии и на собствената му страница (задължително за албуми). За началната страница: показва се като малък надпис над секцията с галерия.', max_length=255, null=True, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Използва се като алтернативен текст (alt) за тази снимка.', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text_bg',
            field=models.CharField(blank=True, help_text='Използва се като алтернативен текст (alt) за тази снимка.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text_en',
            field=models.CharField(blank=True, help_text='Използва се като алтернативен текст (alt) за тази снимка.', max_length=255, null=True),
        ),
    ]
