# Generated by Django 6.0.6 on 2026-07-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_gallery_merge_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='galleryimage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='short_description_bg',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='short_description_en',
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.gallery', verbose_name='Галерия'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Показва се в секцията с галерия на началната страница, или на страницата на албума (и като корична снимка на албума на страницата с галерии, ако е първата по ред).', upload_to='gallery/photos/'),
        ),
        migrations.DeleteModel(
            name='AlbumPhoto',
        ),
        migrations.DeleteModel(
            name='GalleryAlbum',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
