# Generated by Django 6.0.6 on 2026-07-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_gallery_merge_schema_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Показва се разгънат (при клик "Научете повече" / върху картата) в предпочитаните услуги на началната страница.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_bg',
            field=models.TextField(help_text='Показва се разгънат (при клик "Научете повече" / върху картата) в предпочитаните услуги на началната страница.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(help_text='Показва се разгънат (при клик "Научете повече" / върху картата) в предпочитаните услуги на началната страница.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_in_minutes',
            field=models.IntegerField(help_text='Показва се на страницата с услуги и в предпочитаните услуги на началната страница; използва се и за изчисляване на свободните часове за резервация.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Показва се на картата в страницата с услуги и в предпочитаните услуги на началната страница. Ако е празно, се показва градиентен placeholder.', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Показва се в предпочитаните услуги на началната страница, на страницата с услуги и навсякъде в процеса на резервация.', max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_bg',
            field=models.CharField(help_text='Показва се в предпочитаните услуги на началната страница, на страницата с услуги и навсякъде в процеса на резервация.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(help_text='Показва се в предпочитаните услуги на началната страница, на страницата с услуги и навсякъде в процеса на резервация.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Показва се на страницата с услуги и в предпочитаните услуги на началната страница.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='booking_enabled',
            field=models.BooleanField(default=True, help_text='Когато е изключено, скрива всички бутони/линкове за резервация по целия сайт (горно меню, начална страница, страница с услуги, профил на клиента).', verbose_name='Резервации активни'),
        ),
    ]
