# Generated by Django 6.0.6 on 2026-07-26 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_alter_service_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('view_all_reservations', 'Can view all reservations across all specialists'), ('view_specialist_reservations', 'Can view own specialist reservations')], 'verbose_name': 'Резервация', 'verbose_name_plural': 'Резервации'},
        ),
        migrations.AddField(
            model_name='specialist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
