# Generated by Django 6.0.6 on 2026-07-27 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_alter_reservation_options_specialist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='proofing_finalized_at',
            field=models.DateTimeField(blank=True, help_text='Кога клиентът е финализирал избора на снимки от страницата за преглед на снимки от резервацията си. Докато е попълнено, клиентът вижда страницата като заключена за преглед.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='proofing_finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofing_finalizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhotoLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Името на етикета, който клиентът вижда и може да прикачи към снимки при преглед на снимките от своята резервация.', max_length=100, verbose_name='Име')),
                ('cap', models.PositiveIntegerField(help_text='Максимален брой снимки, които клиентът може да маркира с този етикет при преглед на снимките от своята резервация.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимален брой')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ред')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_labels', to='main_app.gallery', verbose_name='Галерия')),
            ],
            options={
                'verbose_name': 'Етикет за преглед на снимки',
                'verbose_name_plural': 'Етикети за преглед на снимки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImageProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_marked', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='main_app.image')),
                ('labels', models.ManyToManyField(blank=True, related_name='images', to='main_app.photolabel')),
            ],
            options={
                'verbose_name': 'Избор на клиент за снимка',
                'verbose_name_plural': 'Избори на клиенти за снимки',
            },
        ),
    ]
