# Generated by Django 6.0.6 on 2026-07-28 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_reservation_proofing_finalized_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproof',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Забележка или коментар, което клиентът е написал за тази снимка при преглед на снимките от своята резервация.', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='imageproof',
            name='is_marked',
            field=models.BooleanField(default=False, help_text='Дали клиентът е маркирал тази снимка като любима при преглед на снимките от своята резервация.'),
        ),
        migrations.AlterField(
            model_name='imageproof',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Етикетите, които клиентът е избрал за тази снимка при преглед на снимките от своята резервация.', related_name='images', to='main_app.photolabel'),
        ),
        migrations.AlterField(
            model_name='photolabel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Определя реда, в който етикетите се показват на клиента при преглед на снимките от своята резервация.', verbose_name='Ред'),
        ),
    ]
