# Generated by Django 6.0.6 on 2026-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_alter_imageproof_comment_alter_imageproof_is_marked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='need_client_review',
            field=models.BooleanField(default=False, help_text='Отбележете, когато галерията е готова и клиентът трябва да прегледа и маркира снимките си в профила си. Показва се на страницата за преглед на снимки в профила на клиента, докато отметката е включена — автоматично се изключва, след като клиентът финализира избора си.'),
        ),
    ]
