# Generated by Django 6.0.6 on 2026-08-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_reservation_need_client_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='proofing_finalized_by',
        ),
    ]
