# Generated by Django 6.0.6 on 2026-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_remove_reservation_proofing_finalized_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='crop_position',
            field=models.CharField(choices=[('top', 'Горе'), ('center', 'В центъра'), ('bottom', 'Долу')], default='center', help_text='Определя коя част от снимката да остане видима, когато тя бъде изрязана да пасне на рамка — в секцията с галерия и началния банер на началната страница, и в плочките на страницата с галерии. Използвайте, ако важната част от снимката е отрязана при показването й.', max_length=10, verbose_name='Позиция при изрязване'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Показва се в секцията с галерия на началната страница, или на страницата на албума (и като корична снимка на албума на страницата с галерии, ако е първата по ред). Оразмерява се и се компресира автоматично при качване — няма нужда снимката да бъде обработена предварително.', upload_to='gallery/photos/'),
        ),
    ]
