# Generated by Django 6.0.6 on 2026-08-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_image_crop_position_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='color_preset',
            field=models.CharField(blank=True, choices=[('custom', 'Персонализирано'), ('warm_earth', 'Топла земя'), ('ocean', 'Океан'), ('monochrome', 'Монохром'), ('forest', 'Гора'), ('rose', 'Розово')], default='custom', help_text='Изберете готова цветова комбинация, за да зададете наведнъж всички цветове по-долу. Прилага се на всички страници на сайта.', max_length=30, verbose_name='Готова цветова комбинация'),
        ),
    ]
