# Generated by Django 6.0.6 on 2026-09-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_siteconfiguration_color_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='font_pair',
            field=models.CharField(choices=[('playfair_montserrat', 'Playfair Display + Montserrat'), ('cormorant_lato', 'Cormorant Garamond + Lato'), ('poppins_opensans', 'Poppins + Open Sans'), ('merriweather_sourcesans', 'Merriweather + Source Sans 3'), ('raleway_roboto', 'Raleway + Roboto'), ('yeseva_ptsans', 'Yeseva One + PT Sans'), ('alegreya_alegreyasans', 'Alegreya + Alegreya Sans'), ('cormorant_ptsans', 'Cormorant Garamond + PT Sans'), ('philosopher_manrope', 'Philosopher + Manrope'), ('oldstandard_nunitosans', 'Old Standard TT + Nunito Sans')], default='playfair_montserrat', help_text='Шрифт по цялата тема на сайта, използван на всички страници.', max_length=30, verbose_name='Двойка шрифтове'),
        ),
    ]
