# Generated by Django 6.0.6 on 2026-09-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_alter_siteconfiguration_font_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='color_preset',
            field=models.CharField(blank=True, choices=[('custom', 'Персонализирано'), ('warm_earth', 'Топла земя'), ('ocean', 'Океан'), ('monochrome', 'Монохром'), ('forest', 'Гора'), ('rose', 'Розово'), ('neon_night', 'Неон нощ'), ('pastel_duo', 'Пастелен дует'), ('emerald_jewel', 'Изумруд'), ('sunset', 'Залез')], default='custom', help_text='Изберете готова цветова комбинация, за да зададете наведнъж всички цветове по-долу. Прилага се на всички страници на сайта.', max_length=30, verbose_name='Готова цветова комбинация'),
        ),
    ]
