# Generated by Django 6.0.6 on 2026-09-04 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_alter_siteconfiguration_color_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='final_gallery',
            field=models.OneToOneField(blank=True, help_text='Готовите, обработени снимки, доставени на клиента. Показва се в профила на клиента под съответната резервация, след като бъде прикачена тук.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_gallery_reservation', to='main_app.gallery'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='finals_delivered_at',
            field=models.DateTimeField(blank=True, help_text='Кога финалните снимки са изпратени на клиента по имейл. Попълва се автоматично при успешно изпращане.', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_type',
            field=models.CharField(choices=[('homepage', 'Начална страница'), ('proofing', 'Преглед на снимки'), ('album', 'Албум'), ('final', 'Финална галерия')], default='album', help_text='Определя къде се показва тази галерия: "Начална страница" — секцията с галерия на началната страница (може да има само една); "Преглед на снимки" — снимки, свързани с преглед на резервация от клиента; "Албум" — показва се като самостоятелен албум на страницата с галерии; "Финална галерия" — готовите, обработени снимки, доставени на клиента.', max_length=20, verbose_name='Тип галерия'),
        ),
    ]
