# Generated by Django 6.0.6 on 2026-09-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_alter_homepage_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, help_text='Показва се като лого в горния колонтитул на сайта.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='photolabel',
            name='name',
            field=models.CharField(help_text='Името на етикета, който клиентът вижда и може да прикачи към снимки при преглед на снимките от своята резервация. Показва се и на специалиста в изгледа "Маркирани снимки".', max_length=100, verbose_name='Име'),
        ),
    ]
