# Generated by Django 6.0.6 on 2026-09-12 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_alter_homepage_logo_alter_photolabel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='surface_paper_color',
            field=models.CharField(default='#FFFFFF', help_text='Фон на картите, панелите и полетата за въвеждане — горното меню, началната страница, галерията, формата за резервация, профила на клиента и прегледа на снимки.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон (карти и панели)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='surface_raised_color',
            field=models.CharField(default='#F6F1E9', help_text='Фон на изскачащите прозорци за вход и за отзив, както и на плочките със специалисти и дните в календара, когато мишката е върху тях.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон (при посочване)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='surface_sunken_color',
            field=models.CharField(default='#F0E9E0', help_text='Фон на тъмните ленти по страниците — секцията с галерията на началната страница, страницата с галерията, лентата със статистики в "За нас", долния колонтитул и заетите часове в календара за резервация.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон (вдълбан)'),
        ),
    ]
