# Generated by Django 6.0.6 on 2026-09-12 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0053_siteconfiguration_surface_paper_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='accent_color',
            field=models.CharField(default='#C89B6A', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Акцентен цвят'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='background_color',
            field=models.CharField(default='#0A0A0B', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='border_color',
            field=models.CharField(default='#2B2B2F', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цвят на рамки'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='color_preset',
            field=models.CharField(blank=True, choices=[('custom', 'Персонализирано'), ('gallery_black', 'Галерийно черно'), ('warm_earth', 'Топла земя'), ('ocean', 'Океан'), ('monochrome', 'Монохром'), ('forest', 'Гора'), ('rose', 'Розово'), ('neon_night', 'Неон нощ'), ('pastel_duo', 'Пастелен дует'), ('emerald_jewel', 'Изумруд'), ('sunset', 'Залез')], default='gallery_black', help_text='Изберете готова цветова комбинация, за да зададете наведнъж всички цветове по-долу. Прилага се на всички страници на сайта.', max_length=30, verbose_name='Готова цветова комбинация'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_color',
            field=models.CharField(default='#EDEAE4', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основен цвят'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='primary_light_color',
            field=models.CharField(default='#FFFFFF', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основен цвят (светъл)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='secondary_color',
            field=models.CharField(default='#A8A8A4', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Вторичен цвят'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='surface_paper_color',
            field=models.CharField(default='#141416', help_text='Фон на картите, панелите и полетата за въвеждане — горното меню, началната страница, галерията, формата за резервация, профила на клиента и прегледа на снимки.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон (карти и панели)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='surface_raised_color',
            field=models.CharField(default='#1D1D20', help_text='Фон на изскачащите прозорци за вход и за отзив, както и на плочките със специалисти и дните в календара, когато мишката е върху тях.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон (при посочване)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='surface_sunken_color',
            field=models.CharField(default='#060607', help_text='Фон на тъмните ленти по страниците — секцията с галерията на началната страница, страницата с галерията, лентата със статистики в "За нас", долния колонтитул и заетите часове в календара за резервация.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон (вдълбан)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='text_color',
            field=models.CharField(default='#F2F2F0', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='text_muted_color',
            field=models.CharField(default='#A3A3A0', help_text='Цвят по цялата тема на сайта, използван на всички страници.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Текст (приглушен)'),
        ),
    ]
