# Generated by Django 6.0.6 on 2026-09-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_apply_gallery_black_to_existing_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photolabel',
            name='cap',
        ),
    ]
