# Generated by Django 6.0.6 on 2026-09-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_remove_photolabel_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='draft_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_galleries', to='main_app.reservation', verbose_name='Чернова към резервация'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Публикувана на'),
        ),
        migrations.AddField(
            model_name='image',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Име на файла при качване'),
        ),
        migrations.AddField(
            model_name='image',
            name='source_size',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер при качване'),
        ),
    ]
