# Generated by Django 6.0.6 on 2026-09-15 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_gallery_draft_reservation_gallery_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='draft_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_galleries', to='main_app.reservation', verbose_name='Чернова към резервация'),
        ),
    ]
