# Generated by Django 6.0.6 on 2026-09-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0058_alter_gallery_draft_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='phone',
            field=models.CharField(help_text='Показва се в профила на клиента и в долния колонтитул (footer) на сайта като линк за обаждане. Показва се и в подканата за вход, която виждат клиенти, записали се по телефона.', max_length=50),
        ),
    ]
