# Generated by Django 6.0.6 on 2026-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_alter_businessinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, help_text='За албуми: показва се на собствената страница на албума. За началната страница: показва се като заглавие на секцията с галерия.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description_bg',
            field=models.TextField(blank=True, help_text='За албуми: показва се на собствената страница на албума. За началната страница: показва се като заглавие на секцията с галерия.', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description_en',
            field=models.TextField(blank=True, help_text='За албуми: показва се на собствената страница на албума. За началната страница: показва се като заглавие на секцията с галерия.', null=True, verbose_name='Описание'),
        ),
    ]
