# Generated by Django 6.0.6 on 2026-09-16 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0060_alter_gallery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='active_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Фон на активния таб за филтриране по категория и на основния бутон "Резервирай" в страницата с услуги.', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят, напр. #4A3728.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон (активен таб и основен бутон)'),
        ),
    ]
