# Generated by Django 6.0.6 on 2026-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0061_siteconfiguration_active_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Показва се разгънат (при клик "Научете повече" / върху картата) в предпочитаните услуги на началната страница и на страницата с услуги. Поддържа удебелен и наклонен текст, списъци и нови редове.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_bg',
            field=models.TextField(help_text='Показва се разгънат (при клик "Научете повече" / върху картата) в предпочитаните услуги на началната страница и на страницата с услуги. Поддържа удебелен и наклонен текст, списъци и нови редове.', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(help_text='Показва се разгънат (при клик "Научете повече" / върху картата) в предпочитаните услуги на началната страница и на страницата с услуги. Поддържа удебелен и наклонен текст, списъци и нови редове.', null=True),
        ),
    ]
