# Generated by Django 6.0.6 on 2026-09-19 12:42

import massageProject.main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0062_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Показва се в секцията с галерия на началната страница, или на страницата на албума (и като корична снимка на албума на страницата с галерии, ако е първата по ред). Оразмерява се и се компресира автоматично при качване — няма нужда снимката да бъде обработена предварително.', upload_to=massageProject.main_app.models.gallery_image_upload_to),
        ),
    ]
