# Generated by Django 6.0.6 on 2026-09-19 12:55

from django.db import migrations, models
from django.db.models import F


def mark_existing_as_purged(apps, schema_editor):
    """Reservations finalised before the purge existed keep their photos: the
    owner asked for this to apply going forward only. Stamping them as already
    purged is what stops the cron command sweeping that backlog."""
    Reservation = apps.get_model('main_app', 'Reservation')
    Reservation.objects.filter(
        proofing_finalized_at__isnull=False, proofs_purged_at__isnull=True,
    ).update(proofs_purged_at=F('proofing_finalized_at'))


def unmark(apps, schema_editor):
    """Reversing only clears the column; nothing was deleted to restore."""
    Reservation = apps.get_model('main_app', 'Reservation')
    Reservation.objects.update(proofs_purged_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0063_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='proofs_purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_as_purged, unmark),
    ]
