# Generated by Django 6.0.6 on 2026-09-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0064_add_proofs_purged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_logo',
            field=models.ImageField(blank=True, help_text='Показва се в горната част на всички имейли до клиентите (код за вход, смяна на паролата, готова галерия, финални снимки). Ако е празно, вместо лого се изписва името на сайта. Препоръчителна ширина до 320px.', null=True, upload_to='branding/', verbose_name='Лого за имейлите'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_reply_to',
            field=models.EmailField(blank=True, help_text='Адресът, на който пристигат отговорите, когато клиент натисне "Отговор" на имейл от сайта. Ако е празно, отговорите отиват на адреса, от който се изпращат имейлите.', max_length=254, verbose_name='Имейл за отговори'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_signature',
            field=models.CharField(blank=True, help_text='Кратък завършващ ред, който се показва след основния текст на всички имейли до клиентите — например "С поздрави, екипът на студиото".', max_length=200, verbose_name='Подпис в имейлите'),
        ),
    ]
