# Generated by Django 6.0.6 on 2026-10-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0066_service_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
