# Generated by Django 6.0.6 on 2026-10-08 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0067_alter_service_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Начало на отсъствието (на кръгъл час или половин час). Показва се в секция „Отсъствия“ в профила; часовете в този период не се предлагат на клиентите за резервация.')),
                ('end', models.DateTimeField(help_text='Край на отсъствието (на кръгъл час или половин час). Показва се в секция „Отсъствия“ в профила; часовете в този период не се предлагат на клиентите за резервация.')),
                ('note', models.CharField(blank=True, default='', help_text='Лична бележка — показва се само в секция „Отсъствия“ в профила на терапевта и на персонала, никога на клиентите.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_off_created', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(help_text='Показва се в секция „Отсъствия“ в профила на терапевта и на персонала.', on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='main_app.specialist')),
            ],
            options={
                'verbose_name': 'Отсъствие',
                'verbose_name_plural': 'Отсъствия',
                'ordering': ['start'],
            },
        ),
    ]
