# Generated by Django 6.0.6 on 2026-10-09 13:57

from django.db import migrations, models


def abort_if_final_galleries_exist(apps, schema_editor):
    Gallery = apps.get_model('main_app', 'Gallery')
    if Gallery.objects.filter(gallery_type='final').exists():
        raise RuntimeError(
            'Final galleries still exist: run `python manage.py purge_final_galleries` first, '
            'then migrate again.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0068_time_off'),
    ]

    operations = [
        migrations.RunPython(abort_if_final_galleries_exist, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='reservation',
            name='final_gallery',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_type',
            field=models.CharField(choices=[('homepage', 'Начална страница'), ('proofing', 'Преглед на снимки'), ('album', 'Албум')], default='album', help_text='Определя къде се показва тази галерия: "Начална страница" — секцията с галерия на началната страница (може да има само една); "Преглед на снимки" — снимки, свързани с преглед на резервация от клиента; "Албум" — показва се като самостоятелен албум на страницата с галерии.', max_length=20, verbose_name='Тип галерия'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='finals_delivered_at',
            field=models.DateTimeField(blank=True, help_text='Кога финалните снимки са предадени на клиента. Когато е попълнено, в профила на клиента, под съответната резервация, се показва редът „Финалните снимки са предадени на <дата>“, а в таблицата с резервации на специалиста и персонала резервацията се води като доставена и бутоните за качване на финали не се показват. Попълва се автоматично при изпращане на финалите по имейл, но може да се зададе или изчисти и на ръка тук. Може да се зададе само след като клиентът е финализирал прегледа на снимките си.', null=True),
        ),
    ]
