# Generated by Django 6.0.6 on 2026-10-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0069_remove_stored_finals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='finals_delivered_at',
            field=models.DateTimeField(blank=True, help_text='Кога финалните снимки са предадени на клиента. Когато е попълнено, в профила на клиента, под съответната резервация, се показва редът „Финалните снимки са предадени на <дата>“, а в таблицата с резервации на специалиста и персонала резервацията се води като доставена и бутонът „Маркирай като предадени“ не се показва. Попълва се от този бутон, но може да се зададе или изчисти и на ръка тук. Може да се зададе само след като клиентът е финализирал прегледа на снимките си.', null=True),
        ),
    ]
